blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/vuejs/test-utils/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Vue.js 2 / test-utils v1
    url: https://github.com/vuejs/vue-test-utils
    about: '@vue/test-utils v1 for Vue.js 2 is in a separate repository'
